target ‘K_BasicDemo’ do
  use_frameworks!

pod 'ReactiveCocoa', '~> 4.2.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry', '~> 1.0.1'
pod 'SDWebImage', '~> 3.8.2'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'AMapLocation', '~> 2.1.1'
pod 'UMengSocialCOM', '~> 5.2.1'
end
